name: Latest blog posts

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 5
          feed_list: "https://dev.to/feed/ikarthiknr,https://medium.com/feed/@ikarthiknr"
          commit_message: "Update latest blog posts"
